version: "3.3"
services:
  mongodb:
    container_name: docker-mongo
    ports:
      - "2717:27017"
    image: mongo:latest
    environment:
      - MONGODB_USER="root"
      - MONGODB_PASS="maverick"
    volumes:
      - "mongodb-data:/data/db"
volumes:
  mongodb-data: {}