server:
  port: ${PORT:0}

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  application:
    name: service-cursos
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/escuela?allowPublicKeyRetrieval=true&useSSL=false
    username: fernando
    password: admin2022
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true

config:
  balanceador:
    test: balanceador_test
    