server:
  port: ${PORT:0}
  
spring:
  application:
    name: service-usuarios
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:54320/micro-usuarios?allowPublicKeyRetrieval=true&useSSL=false
    username: postgres
    password: Maverick77
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc:
          lob:
            non-contextual-creation: true
        
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    
    
    
    