server:
  port: ${PORT:0}
  
spring:
  application:
    name: service-respuestas
  data:
    mongodb:
      uri: mongodb://localhost:2717/curso
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
        
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
